-- 12. MASKING POLICY (4 ROLES)
USE ROLE ACCOUNTADMIN;
USE DATABASE HOSPITAL_DW;
USE SCHEMA GOVERNANCE;

-- STEP 1: UNSET EXISTING POLICIES (prevent conflicts on re-run)
ALTER TABLE IF EXISTS HOSPITAL_DW.CORE.CORE_PATIENTS
    MODIFY COLUMN PHONE     UNSET MASKING POLICY;

ALTER TABLE IF EXISTS HOSPITAL_DW.CORE.CORE_PATIENTS
    MODIFY COLUMN EMAIL     UNSET MASKING POLICY;

ALTER TABLE IF EXISTS HOSPITAL_DW.CORE.CORE_PATIENTS
    MODIFY COLUMN FULL_NAME UNSET MASKING POLICY;

ALTER DYNAMIC TABLE IF EXISTS HOSPITAL_DW.MART.DIM_PATIENT
    MODIFY COLUMN PHONE     UNSET MASKING POLICY;

ALTER DYNAMIC TABLE IF EXISTS HOSPITAL_DW.MART.DIM_PATIENT
    MODIFY COLUMN EMAIL     UNSET MASKING POLICY;

ALTER DYNAMIC TABLE IF EXISTS HOSPITAL_DW.MART.DIM_PATIENT
    MODIFY COLUMN FULL_NAME UNSET MASKING POLICY;


-- STEP 2: CREATE MASKING POLICIES
CREATE OR REPLACE MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_PHONE AS
    (VAL VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN')
            THEN VAL
        WHEN CURRENT_ROLE() IN ('HOSPITAL_ENGINEER_ROLE', 'HOSPITAL_MANAGER_ROLE')
            THEN VAL
        WHEN CURRENT_ROLE() = 'HOSPITAL_ANALYST_ROLE'
            THEN CASE
                     WHEN VAL IS NULL THEN NULL
                     ELSE CONCAT('******', RIGHT(VAL, 4))
                 END
        ELSE    -- HOSPITAL_VIEWER_ROLE and any unlisted roles
            CASE
                WHEN VAL IS NULL THEN NULL
                ELSE '**********'
            END
    END;


-- EMAIL MASKING
CREATE OR REPLACE MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_EMAIL AS
    (VAL VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN')
            THEN VAL
        WHEN CURRENT_ROLE() IN ('HOSPITAL_ENGINEER_ROLE', 'HOSPITAL_MANAGER_ROLE')
            THEN VAL
        WHEN CURRENT_ROLE() = 'HOSPITAL_ANALYST_ROLE'
            THEN CASE
                     WHEN VAL IS NULL                   THEN NULL
                     WHEN CHARINDEX('@', VAL) > 0       THEN CONCAT('****', SUBSTR(VAL, CHARINDEX('@', VAL)))
                     ELSE '****'
                 END
        ELSE    -- HOSPITAL_VIEWER_ROLE and any unlisted roles
            CASE
                WHEN VAL IS NULL THEN NULL
                ELSE '****'
            END
    END;


-- PATIENT NAME MASKING
CREATE OR REPLACE MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_PATIENT_NAME AS
    (VAL VARCHAR) RETURNS VARCHAR ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN')
            THEN VAL
        WHEN CURRENT_ROLE() IN ('HOSPITAL_ENGINEER_ROLE', 'HOSPITAL_MANAGER_ROLE')
            THEN VAL
        WHEN CURRENT_ROLE() = 'HOSPITAL_ANALYST_ROLE'
            THEN CASE
                     WHEN VAL IS NULL THEN NULL
                     WHEN CHARINDEX(' ', TRIM(VAL)) > 0
                         THEN CONCAT(LEFT(TRIM(VAL), 1), '. ', SUBSTR(TRIM(VAL), CHARINDEX(' ', TRIM(VAL)) + 1))
                     ELSE CONCAT(LEFT(TRIM(VAL), 1), '.')
                 END
        ELSE    -- HOSPITAL_VIEWER_ROLE and any unlisted roles
            CASE
                WHEN VAL IS NULL THEN NULL
                ELSE '****'
            END
    END;



-- STEP 3: APPLY POLICIES TO CORE LAYER
ALTER TABLE HOSPITAL_DW.CORE.CORE_PATIENTS
    MODIFY COLUMN PHONE     SET MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_PHONE;

ALTER TABLE HOSPITAL_DW.CORE.CORE_PATIENTS
    MODIFY COLUMN EMAIL     SET MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_EMAIL;

ALTER TABLE HOSPITAL_DW.CORE.CORE_PATIENTS
    MODIFY COLUMN FULL_NAME SET MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_PATIENT_NAME;


-- STEP 4: APPLY POLICIES TO MART LAYER (DIM_PATIENT)
ALTER DYNAMIC TABLE HOSPITAL_DW.MART.DIM_PATIENT
    MODIFY COLUMN PHONE     SET MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_PHONE;

ALTER DYNAMIC TABLE HOSPITAL_DW.MART.DIM_PATIENT
    MODIFY COLUMN EMAIL     SET MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_EMAIL;

ALTER DYNAMIC TABLE HOSPITAL_DW.MART.DIM_PATIENT
    MODIFY COLUMN FULL_NAME SET MASKING POLICY HOSPITAL_DW.GOVERNANCE.MASK_PATIENT_NAME;


-- STEP 5: VERIFICATION — expected output per role
SHOW MASKING POLICIES IN SCHEMA HOSPITAL_DW.GOVERNANCE;
