-- 11. RBAC (4 ROLES)
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HOSPITAL_WH;
USE DATABASE HOSPITAL_DW;

-- CREATE ROLES
CREATE OR REPLACE ROLE HOSPITAL_ENGINEER_ROLE
    COMMENT = 'Data Engineers: full DDL+DML on all layers, sees raw PII';

CREATE OR REPLACE ROLE HOSPITAL_MANAGER_ROLE
    COMMENT = 'Managers: read-only on RAW + CORE + MART, sees raw PII';

CREATE OR REPLACE ROLE HOSPITAL_ANALYST_ROLE
    COMMENT = 'Analysts: read-only on CORE + MART, partially masked PII';

CREATE OR REPLACE ROLE HOSPITAL_VIEWER_ROLE
    COMMENT = 'Business Viewers: read-only on MART only, fully masked PII';

-- ROLE HIERARCHY
GRANT ROLE HOSPITAL_MANAGER_ROLE  TO ROLE HOSPITAL_ENGINEER_ROLE;
GRANT ROLE HOSPITAL_ANALYST_ROLE  TO ROLE HOSPITAL_MANAGER_ROLE;
GRANT ROLE HOSPITAL_VIEWER_ROLE   TO ROLE HOSPITAL_ANALYST_ROLE;

-- Roll up to SYSADMIN for admin oversight
GRANT ROLE HOSPITAL_ENGINEER_ROLE TO ROLE SYSADMIN;

-- CREATE USERS
CREATE OR REPLACE USER HOSPITAL_ENGINEER_USER
    PASSWORD          = 'Engineer@123'
    DEFAULT_ROLE      = HOSPITAL_ENGINEER_ROLE
    DEFAULT_WAREHOUSE = HOSPITAL_WH
    COMMENT           = 'Data Engineer login';

CREATE OR REPLACE USER HOSPITAL_MANAGER_USER
    PASSWORD          = 'Manager@123'
    DEFAULT_ROLE      = HOSPITAL_MANAGER_ROLE
    DEFAULT_WAREHOUSE = HOSPITAL_WH
    COMMENT           = 'Hospital Manager login';

CREATE OR REPLACE USER HOSPITAL_ANALYST_USER
    PASSWORD          = 'Analyst@123'
    DEFAULT_ROLE      = HOSPITAL_ANALYST_ROLE
    DEFAULT_WAREHOUSE = HOSPITAL_WH
    COMMENT           = 'Data Analyst login';

CREATE OR REPLACE USER HOSPITAL_VIEWER_USER
    PASSWORD          = 'Viewer@123'
    DEFAULT_ROLE      = HOSPITAL_VIEWER_ROLE
    DEFAULT_WAREHOUSE = HOSPITAL_WH
    COMMENT           = 'Business Viewer login';

-- GRANT ROLES TO USERS
GRANT ROLE HOSPITAL_ENGINEER_ROLE TO USER HOSPITAL_ENGINEER_USER;
GRANT ROLE HOSPITAL_MANAGER_ROLE  TO USER HOSPITAL_MANAGER_USER;
GRANT ROLE HOSPITAL_ANALYST_ROLE  TO USER HOSPITAL_ANALYST_USER;
GRANT ROLE HOSPITAL_VIEWER_ROLE   TO USER HOSPITAL_VIEWER_USER;


-- ENGINEER ROLE ACCESS
GRANT USAGE ON WAREHOUSE HOSPITAL_WH TO ROLE HOSPITAL_ENGINEER_ROLE;
GRANT USAGE ON DATABASE HOSPITAL_DW  TO ROLE HOSPITAL_ENGINEER_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE HOSPITAL_DW TO ROLE HOSPITAL_ENGINEER_ROLE;

-- RAW
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HOSPITAL_DW.RAW TO ROLE HOSPITAL_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HOSPITAL_DW.RAW TO ROLE HOSPITAL_ENGINEER_ROLE;

-- CORE
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA HOSPITAL_DW.CORE TO ROLE HOSPITAL_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA HOSPITAL_DW.CORE TO ROLE HOSPITAL_ENGINEER_ROLE;

-- MART
GRANT ALL PRIVILEGES ON ALL TABLES             IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON ALL DYNAMIC TABLES     IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON ALL VIEWS              IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON ALL MATERIALIZED VIEWS IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ENGINEER_ROLE;

GRANT ALL PRIVILEGES ON FUTURE TABLES             IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE DYNAMIC TABLES     IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE VIEWS              IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ENGINEER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE MATERIALIZED VIEWS IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ENGINEER_ROLE;


-- MANAGER ROLE ACCESS
GRANT USAGE ON WAREHOUSE HOSPITAL_WH TO ROLE HOSPITAL_MANAGER_ROLE;
GRANT USAGE ON DATABASE HOSPITAL_DW  TO ROLE HOSPITAL_MANAGER_ROLE;

-- RAW schema: SELECT only
GRANT USAGE  ON SCHEMA HOSPITAL_DW.RAW TO ROLE HOSPITAL_MANAGER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA HOSPITAL_DW.RAW TO ROLE HOSPITAL_MANAGER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HOSPITAL_DW.RAW TO ROLE HOSPITAL_MANAGER_ROLE;

-- CORE schema: SELECT only
GRANT USAGE  ON SCHEMA HOSPITAL_DW.CORE TO ROLE HOSPITAL_MANAGER_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA HOSPITAL_DW.CORE TO ROLE HOSPITAL_MANAGER_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HOSPITAL_DW.CORE TO ROLE HOSPITAL_MANAGER_ROLE;

-- MART schema: SELECT on all object types
GRANT USAGE  ON SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_MANAGER_ROLE;
GRANT SELECT ON ALL TABLES             IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_MANAGER_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES     IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_MANAGER_ROLE;
GRANT SELECT ON ALL VIEWS              IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_MANAGER_ROLE;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_MANAGER_ROLE;

GRANT SELECT ON FUTURE TABLES             IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_MANAGER_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES     IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_MANAGER_ROLE;
GRANT SELECT ON FUTURE VIEWS              IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_MANAGER_ROLE;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_MANAGER_ROLE;


-- ANALYST ROLE ACCESS
GRANT USAGE ON WAREHOUSE HOSPITAL_WH TO ROLE HOSPITAL_ANALYST_ROLE;
GRANT USAGE ON DATABASE HOSPITAL_DW  TO ROLE HOSPITAL_ANALYST_ROLE;

-- CORE schema: SELECT only
GRANT USAGE  ON SCHEMA HOSPITAL_DW.CORE TO ROLE HOSPITAL_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA HOSPITAL_DW.CORE TO ROLE HOSPITAL_ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HOSPITAL_DW.CORE TO ROLE HOSPITAL_ANALYST_ROLE;

-- MART schema: SELECT on all object types
GRANT USAGE  ON SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ANALYST_ROLE;
GRANT SELECT ON ALL TABLES             IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ANALYST_ROLE;
GRANT SELECT ON ALL DYNAMIC TABLES     IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ANALYST_ROLE;
GRANT SELECT ON ALL VIEWS              IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ANALYST_ROLE;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ANALYST_ROLE;

GRANT SELECT ON FUTURE TABLES             IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ANALYST_ROLE;
GRANT SELECT ON FUTURE DYNAMIC TABLES     IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ANALYST_ROLE;
GRANT SELECT ON FUTURE VIEWS              IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ANALYST_ROLE;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_ANALYST_ROLE;


-- VIEWER ROLE ACCESS
GRANT USAGE ON WAREHOUSE HOSPITAL_WH TO ROLE HOSPITAL_VIEWER_ROLE;
GRANT USAGE ON DATABASE HOSPITAL_DW  TO ROLE HOSPITAL_VIEWER_ROLE;
GRANT USAGE ON SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_VIEWER_ROLE;

GRANT SELECT ON ALL DYNAMIC TABLES     IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_VIEWER_ROLE;
GRANT SELECT ON ALL VIEWS              IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_VIEWER_ROLE;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_VIEWER_ROLE;

GRANT SELECT ON FUTURE DYNAMIC TABLES     IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_VIEWER_ROLE;
GRANT SELECT ON FUTURE VIEWS              IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_VIEWER_ROLE;
GRANT SELECT ON FUTURE MATERIALIZED VIEWS IN SCHEMA HOSPITAL_DW.MART TO ROLE HOSPITAL_VIEWER_ROLE;


-- VERIFICATION
SHOW ROLES;
SHOW USERS;

SHOW GRANTS TO ROLE HOSPITAL_ENGINEER_ROLE;
SHOW GRANTS TO ROLE HOSPITAL_MANAGER_ROLE;
SHOW GRANTS TO ROLE HOSPITAL_ANALYST_ROLE;
SHOW GRANTS TO ROLE HOSPITAL_VIEWER_ROLE;
