USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HOSPITAL_WH;
USE DATABASE HOSPITAL_DW;
USE SCHEMA RAW;

-- SINGLE INTERNAL STAGE
CREATE OR REPLACE STAGE HOSPITAL_DW.RAW.HOSPITAL_CSV_STAGE
    FILE_FORMAT = HOSPITAL_DW.RAW.CSV_FILE_FORMAT
    COMMENT = 'Internal stage for all hospital CSV files';
